### PR TITLE
Updates for the new CSV.jl version

### PR DESCRIPTION
**Pull request by davidanthoff**
@quinnj, could you have a quick look whether this makes sense to you? This is remove the `copycols` case, and then I'm also migrating things to `DataFrame!(CSV.File())`. I'll merge this once you have tagged the new CSV.jl. If you want me to run the benchmark before then on `CSV#master`, just ping me!

### CODE REVIEW

**Comment by quinnj** [comment]
Sorry for the slow response here; this looks great! I'm glad we don't need to special-case `copycols` anymore. As I've been doing some benchmarking lately vs. R/python, the only other recommendation I have is to set `pool=false`. No one else does pooling/factors by default, and currently there's a bit of a performance hit for doing so in CSV.jl.

CSV.jl 0.7 also introduced a `lazystrings=true` option that can speed parsing up a bit, but the vector you get back is read-only (like previous 0.6 release). For string-heavy files, it can speed things up because you're avoiding all the individual allocations, but in general the impact is smaller (like for mixed.csv, it doesn't make too big of a difference). I don't think we need to benchmark with it, but just as an FYI.

**Comment by davidanthoff** [comment]
I have a run going right now with the content of this PR. I think generally it makes sense to have at least as one configuration whatever is the default that users get if they don't dig deeper.

BUT, we can certainly add more runs, e.g. one with `pool=false` and one with `lazystrings=true`. They are probably mutually exclusive, so I would have to add two runs, right?

Just out of curiosity: if `pool=true` slows things down, why not make `false` the default?

**Comment by quinnj** [comment]
Speed isn't always the most important priority :)

But it actually shouldn't be a problem once https://github.com/JuliaData/CSV.jl/pull/676 is released. I figured out a way to make it basically as fast.

So let's not worry about doing anything with `pool`, but I'd still be curious to see the kind of difference `lazystrings=true` would make on various files, in particular the mixed vs. all string files.

**Comment by davidanthoff** [comment]
Cool, I'll add the lazystring option for the next run.

I did one run that was a bit misconfigured, so I'm redoing things right now, but the parallel thing on Windows now seems to parallelize _really_ well for CSV.jl, from what I saw so far. I'll try to do the Mac and Linux runs redone as well, maybe once I've also added the `lazystrings`.

**Pull request merged**
